# Generated by Django 5.2.3 on 2025-06-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('lugar', models.TextField()),
                ('hora_habre', models.TimeField()),
                ('hora_cierra', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(null=True, upload_to='catalogo/upload/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fermentacion', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Envasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('volumen_ml', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GraduacionAlcoholica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Catalogo.servicio')),
                ('canillas', models.IntegerField()),
                ('disponible', models.BooleanField()),
            ],
            bases=('Catalogo.servicio',),
        ),
        migrations.CreateModel(
            name='Chopera',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Catalogo.servicio')),
                ('litros', models.IntegerField()),
            ],
            bases=('Catalogo.servicio',),
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('ibu', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='catalogo/upload/img/')),
                ('disponible', models.BooleanField(default=True)),
                ('estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.categoria')),
                ('porcentaje_alcohol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.graduacionalcoholica')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(null=True, upload_to='catalogo/upload/img/')),
                ('cerveza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.cerveza')),
                ('envasado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.envasado')),
            ],
        ),
    ]
