# Generated by Django 5.2.3 on 2025-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cervezas/'),
        ),
    ]
